#!/usr/bin/env bash
# test_trace_scorecard_docs.sh — regression sensor for the frozen
# trace-scorecard v1 contract doc + eval-doc pointers (issue #104, feature
# scorecard-contract-docs, plan Phase 4).
#
# Executable spec (this sensor IS the spec — plan D3/D5). Pinned conventions:
#
#   1. Contract doc  docs/evaluation/trace-scorecard.v1.json  exists, parses
#      with jq, and — mirroring the trace-summary.v1.json precedent —
#      declares `"scorecard_schema_version": 1` (a JSON number) plus its
#      field vocabulary:
#        * `required_top_level`: array of every top-level key the script
#          emits — checked for DRIFT IN BOTH DIRECTIONS against a scorecard
#          actually generated by scripts/trace-scorecard.sh in this run
#          (doc keys == emitted keys as sets; a doc that under- or
#          over-declares fails);
#        * `bucket_fields`: array of every per-bucket key inside
#          by_version[] — same both-direction drift check against a
#          generated bucket.
#   2. Honest metric doctrine documented: the doc names the DEFERRED metrics
#      (review-blocking findings; per-feature tool-call attribution) and
#      that they need an additive trace-summary v1.x extension — never
#      fabricated from what v1 carries.
#   3. #62 mapping intent documented, not forked: the doc states that
#      by_version[].issues[] rows are run aggregates (case-level eval
#      scorecards are a different animal) and maps them to a #62 results[]
#      entry with boundary "trace-aggregate"; open-world rule stated
#      (consumers reject unknown majors, additive keys allowed in 1.x).
#   4. Doc pointers (one line each, plan Phase 4):
#        * docs/evaluation/observability-and-trace-schema.md mentions
#          trace-scorecard.sh inside its "## Reporting A Trace" section;
#        * docs/evaluation/cost-efficiency-evals.md points at the
#          trace-scorecard artifact as the cross-run metrics artifact.
#      The existing schema-docs sensor (test_trace_schema_docs.sh) must
#      STAY green after those edits — enforced by running it here.
#
# Exit codes: 0 docs contract honored · 1 an obligation regressed (RED
# today: the contract doc and both pointers do not exist).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCORECARD_SH="${ROOT}/scripts/trace-scorecard.sh"
CONTRACT_DOC="${ROOT}/docs/evaluation/trace-scorecard.v1.json"
OBS_DOC="${ROOT}/docs/evaluation/observability-and-trace-schema.md"
COST_DOC="${ROOT}/docs/evaluation/cost-efficiency-evals.md"
SCHEMA_DOCS_SENSOR="${ROOT}/tests/scripts/test_trace_schema_docs.sh"
SCORECARD_REL="tests/evals/scorecards/trace-scorecard.json"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

fails=0
fail() {
  printf 'FAIL: %s\n' "$*" >&2
  fails=$((fails + 1))
}
hard_fail() {
  printf 'FAIL: %s\n' "$*" >&2
  exit 1
}
note() {
  printf 'note: %s\n' "$*"
}

unset TRACE_ISSUE TRACE_PARENT_SPAN_ID TRACE_INPUT_TOKENS TRACE_OUTPUT_TOKENS \
  REQUIRE_FEATURES_COMPLETE 2>/dev/null || true

# --- Prerequisites -----------------------------------------------------------
command -v jq >/dev/null 2>&1 \
  || hard_fail "jq is required (the scorecard contract and this sensor are jq-driven)"
[ -x "$SCORECARD_SH" ] \
  || hard_fail "scripts/trace-scorecard.sh not found or not executable (${SCORECARD_SH}) — features scorecard-core/honesty must land before their contract can be documented"

# --- Generate a real scorecard to cross-check the doc against (no drift) -------
# Minimal fixture that populates every section: one aggregated run with a
# tokens object, one unresolved-mixed run, one missing summary, one skipped
# (unknown major) summary.
FX_ROOT="${TMP_DIR}/fixture-root"
ISSUES_DIR="${FX_ROOT}/.copilot-tracking/issues"
mkdir -p "${ISSUES_DIR}/issue-30" "${ISSUES_DIR}/issue-31" \
  "${ISSUES_DIR}/issue-32" "${ISSUES_DIR}/issue-33"

write_summary() {
  local issue="$1" versions="$2" schema="$3"
  cat > "${ISSUES_DIR}/issue-${issue}/trace-summary.json" <<EOF
{
  "summary_schema_version": ${schema},
  "trace_file": "${ISSUES_DIR}/issue-${issue}/trace.jsonl",
  "issue": ${issue},
  "harness_versions": ${versions},
  "finished": true,
  "final_outcome": "pass",
  "span_counts": {"total": 2, "invalid_lines": 0, "by_type": {"lifecycle": 2}},
  "wall_clock": {"first_timestamp": "2026-07-04T10:00:00Z", "last_timestamp": "2026-07-04T10:00:30Z", "elapsed_seconds": 30},
  "stages": [{"step": "preflight", "spans": 1, "duration_ms": null}],
  "tools": [{"name": "git", "calls": 1, "fail_calls": 0, "duration_ms": null}],
  "tokens": {"input": 10, "output": 2},
  "loop_indicators": [],
  "red_reentry": [],
  "deviations": {"count": 0, "feature_ids": []}
}
EOF
}
write_summary 30 '["dA"]' 1
write_summary 31 '["dB", "dC"]' 1   # multi-version, no trace → mixed
write_summary 33 '["dD"]' 2        # unknown major → skipped
printf '%s\n' \
  '{"schema_version":1,"timestamp":"2026-07-04T08:00:00Z","span":"lifecycle","harness.issue":32,"harness.version":"dA","harness.lifecycle_step":"preflight"}' \
  > "${ISSUES_DIR}/issue-32/trace.jsonl"

rc=0
"$SCORECARD_SH" --root "$FX_ROOT" > /dev/null 2>&1 || rc=$?
if [ "$rc" -ne 0 ]; then
  hard_fail "trace-scorecard.sh --root <fixture> exited ${rc} — cannot generate the reference scorecard for the drift check"
fi
GENERATED="${FX_ROOT}/${SCORECARD_REL}"
[ -f "$GENERATED" ] \
  || hard_fail "reference scorecard not written (${GENERATED})"

# --- 1. Contract doc exists, parses, declares the version -----------------------
if [ ! -f "$CONTRACT_DOC" ]; then
  fail "contract doc docs/evaluation/trace-scorecard.v1.json not found (${CONTRACT_DOC}) — feature scorecard-contract-docs must freeze the scorecard v1 contract (sibling of trace-summary.v1.json, same style)"
else
  jq empty "$CONTRACT_DOC" >/dev/null 2>&1 \
    || fail "contract doc must parse as JSON (mirror the trace-summary.v1.json precedent)"
  jq -e '.scorecard_schema_version == 1 and (.scorecard_schema_version | type == "number")' \
    "$CONTRACT_DOC" >/dev/null 2>&1 \
    || fail "contract doc must declare scorecard_schema_version 1 as a JSON number"

  # --- 1a. Envelope vocabulary: no drift, both directions ----------------------
  doc_top="$(jq -c '(.required_top_level // []) | sort' "$CONTRACT_DOC" 2>/dev/null)"
  emitted_top="$(jq -c 'keys | sort' "$GENERATED")"
  if [ "$doc_top" = "$emitted_top" ]; then
    note "required_top_level matches the emitted envelope (${emitted_top})"
  else
    fail "required_top_level drift — doc declares ${doc_top:-<missing>} but scripts/trace-scorecard.sh emits ${emitted_top} (sets must match exactly, both directions)"
  fi

  # --- 1b. Bucket vocabulary: no drift, both directions ------------------------
  doc_bucket="$(jq -c '(.bucket_fields // []) | sort' "$CONTRACT_DOC" 2>/dev/null)"
  emitted_bucket="$(jq -c '.by_version[0] | keys | sort' "$GENERATED")"
  if [ "$doc_bucket" = "$emitted_bucket" ]; then
    note "bucket_fields matches the emitted by_version bucket (${emitted_bucket})"
  else
    fail "bucket_fields drift — doc declares ${doc_bucket:-<missing>} but scripts/trace-scorecard.sh emits ${emitted_bucket} (sets must match exactly, both directions)"
  fi

  # --- 2. Computable-vs-deferred metrics doctrine -------------------------------
  jq -e 'tostring | contains("review-blocking")' "$CONTRACT_DOC" >/dev/null 2>&1 \
    || fail "contract doc must name review-blocking findings as a DEFERRED metric (v1 summaries carry no per-verdict field)"
  jq -e 'tostring | contains("per-feature")' "$CONTRACT_DOC" >/dev/null 2>&1 \
    || fail "contract doc must name per-feature tool-call attribution as a DEFERRED metric (v1 tools[] has no feature dimension)"
  jq -e 'tostring | contains("v1.x")' "$CONTRACT_DOC" >/dev/null 2>&1 \
    || fail "contract doc must state that deferred metrics need an additive trace-summary v1.x extension — never fabricated from what v1 carries"

  # --- 3. #62 mapping intent + open-world rule ----------------------------------
  jq -e 'tostring | contains("trace-aggregate")' "$CONTRACT_DOC" >/dev/null 2>&1 \
    || fail "contract doc must document the #62 mapping: issues[] rows map to a #62 results[] entry with boundary \"trace-aggregate\""
  jq -e 'tostring | contains("#62")' "$CONTRACT_DOC" >/dev/null 2>&1 \
    || fail "contract doc must reference #62 explicitly (mapping documented, not forked: run aggregates are not case-level eval scorecard rows)"
  jq -e 'tostring | test("unknown major")' "$CONTRACT_DOC" >/dev/null 2>&1 \
    || fail "contract doc must state the open-world rule (consumers reject unknown majors; additive keys allowed in 1.x) — same doctrine as trace-summary v1"
fi

# --- 4a. observability doc: reporting section points at the scorecard -----------
reporting_section="$(awk '/^## Reporting A Trace/{flag=1; next} /^## /{flag=0} flag' "$OBS_DOC")"
if printf '%s' "$reporting_section" | grep -q 'trace-scorecard.sh'; then
  note "observability doc reporting section mentions trace-scorecard.sh"
else
  fail "docs/evaluation/observability-and-trace-schema.md must mention scripts/trace-scorecard.sh in its '## Reporting A Trace' section (the cross-run consumer of trace-summary v1)"
fi

# --- 4b. cost-efficiency doc: scorecard as the cross-run metrics artifact -------
if grep -q 'trace-scorecard' "$COST_DOC"; then
  note "cost-efficiency doc points at the trace-scorecard artifact"
else
  fail "docs/evaluation/cost-efficiency-evals.md must point at the trace-scorecard artifact (tests/evals/scorecards/trace-scorecard.json) as the cross-run metrics artifact"
fi

# --- 4c. The existing schema-docs sensor must stay green ------------------------
if [ -x "$SCHEMA_DOCS_SENSOR" ]; then
  rc=0
  "$SCHEMA_DOCS_SENSOR" > "${TMP_DIR}/schema-docs.out" 2>&1 || rc=$?
  if [ "$rc" -eq 0 ]; then
    note "test_trace_schema_docs.sh stays green"
  else
    fail "test_trace_schema_docs.sh regressed (exit ${rc}) — the doc-pointer edits must not break the existing schema-docs contract: $(tail -3 "${TMP_DIR}/schema-docs.out" | tr '\n' ' ')"
  fi
else
  fail "tests/scripts/test_trace_schema_docs.sh not found or not executable — cannot prove the schema-docs contract stays green"
fi

# --- Verdict --------------------------------------------------------------------
if [ "$fails" -gt 0 ]; then
  printf 'test_trace_scorecard_docs: %d failure(s)\n' "$fails" >&2
  exit 1
fi
echo "test_trace_scorecard_docs: PASS"
