#!/usr/bin/env bash
# test_log_handback.sh — regression sensor for scripts/log-handback.sh
# (issue #95, feature log-handback-helper, plan Phase 1; updated issue #332,
# feature trace-only-handback).
#
# Contract under test (plan D1–D6 + conductor-resolved decisions 2026-07-04;
# updated 2026-07-22: direct Action Log write retired, renderer-based):
#
#   scripts/log-handback.sh <role> <lifecycle_step> <feature_id> <outcome> <summary...>
#
#   Turns ONE decision/handback event into one agent span appended to the MAIN
#   checkout root's .copilot-tracking/issues/issue-NN/trace.jsonl.  After
#   writing the span, scripts/render-action-log.sh is called in ISSUE-NUMBER
#   mode to regenerate the ## Action Log section of the WORKTREE's
#   .copilot-tracking/issues/issue-NN/progress.md from all spans in the trace.
#
#   PINNED CLI / ENV CONVENTIONS (spec for the implementer):
#
#   - Roles (closed enum, D1):
#       conductor | planning-subagent | generator-subagent |
#       implementation-subagent | test-subagent | code-review-subagent
#   - Lifecycle steps (closed subset of the #92 enum, D2):
#       plan_handback | feature_start | red_handback | impl_handback |
#       green_handback | review_verdict | deviation
#   - Outcomes (closed enum): pass | fail | blocked
#   - <summary...> is variadic: all remaining args are joined with single
#     spaces into one summary line.
#   - Span shape (conductor-resolved): span=agent,
#     gen_ai.operation.name=invoke_agent, gen_ai.agent.name=<role>,
#     harness.lifecycle_step=<step>, harness.feature_id=<feature_id>,
#     harness.outcome=<outcome>, harness.summary=<summary>. Must pass the
#     #92 contract filter (agent spans require gen_ai.operation.name +
#     gen_ai.agent.name plus the common five).
#   - Action Log line format (D3), appended under the '## Action Log'
#     heading of the worktree progress.md:
#       - [<role>] <lifecycle_step> <feature_id> <outcome> — <summary>
#   - Token passthrough (D5, convention PINNED HERE as env — NOT trailing
#     args, to avoid ambiguity with the variadic summary):
#       TRACE_INPUT_TOKENS  → gen_ai.usage.input_tokens  (JSON number)
#       TRACE_OUTPUT_TOKENS → gen_ai.usage.output_tokens (JSON number)
#     Each is forwarded independently and ONLY when it is a pure decimal
#     integer; unset or non-numeric → the key is ABSENT (omit, never fake;
#     a non-numeric value is not an error — the call still succeeds).
#   - Failure-mode passthrough (issue #99, feature failure-mode-span-plumbing,
#     convention PINNED HERE — mirrors the token passthrough):
#       TRACE_FAILURE_MODE → harness.failure_mode (JSON string)
#     Forwarded ONLY when the value is a member of the contract's closed
#     failure_modes enum (docs/evaluation/trace-schema.v1.json). Unset →
#     key ABSENT. Out-of-enum → key OMITTED, stderr warning naming the
#     failure mode env/attribute, call still exits 0 (omit, never fake,
#     never hard-fail — soft input, unlike role/step/outcome).
#     PINNED: the passthrough attaches on ANY lifecycle step when set —
#     the deviation/failure convention is prose in
#     docs/evaluation/failure-mode-taxonomy.md; enforcement stays soft
#     (open-world optional field, no step gate). The Action Log bullet
#     format (D3) is UNCHANGED by the failure mode.
#   - Instruction-files passthrough (issue #300, feature
#     instruction-files-span, convention PINNED HERE — mirrors the token /
#     failure-mode passthrough):
#       TRACE_INSTRUCTION_FILES → harness.instruction_files (JSON string)
#     Forwarded VERBATIM whenever it is set and non-empty (a space/comma-
#     separated list of instruction-file paths). Unlike the failure mode
#     there is NO closed enum — any non-empty string is accepted as-is and
#     redacted by trace-lib like every other attribute. Unset or empty →
#     the key is ABSENT (omit, never fake; empty is not an error — the call
#     still exits 0). Attaches on ANY lifecycle step; the Action Log bullet
#     format (D3) is UNCHANGED.
#   - Failure semantics (conductor-resolved):
#       * Validation failures (bad role/step/outcome, missing args) →
#         non-zero exit, NO span written.
#       * trace-lib.sh absent → tracing degrades (span skipped), renderer
#         called (warn-never-fail, nothing to render); warns on stderr
#         (mentioning trace-lib); exits 0. No trace file is created.
#       * progress.md missing or lacking '## Action Log' section → span IS
#         written; renderer warns and exits 0; log-handback exits 0.
#   - Redaction: the span is redacted by trace-lib before writing;
#     progress.md's Action Log is regenerated by render-action-log.sh from
#     the already-redacted trace content.
#   - Loop-2 hardening (pinned by the negative cases below):
#       * feature_id is a single token matching [A-Za-z0-9._-]+ ('-'
#         included); whitespace or ']' would corrupt the bullet shape and
#         tuple parsing → validation failure, nothing written.
#       * The summary is one-line by contract: embedded newlines/CRs are
#         flattened to spaces before the span is written (one span with
#         flattened text; the renderer writes the same flattened text).
#
# Fixture style follows test_trace_review_gate.sh: throwaway MAIN repo +
# linked feature/issue-NN-* worktrees, helper invoked FROM THE WORKTREE
# (conductor context), pinned PATH, contract filter lifted verbatim from
# test_trace_schema.sh.
#
# Exit codes: 0 handback contract honored · 1 a contract obligation regressed.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HELPER="${ROOT}/scripts/log-handback.sh"
LIB="${ROOT}/scripts/trace-lib.sh"
RENDERER="${ROOT}/scripts/render-action-log.sh"
CONTRACT="${ROOT}/docs/evaluation/trace-schema.v1.json"

# shellcheck source=/dev/null
source "${ROOT}/tests/scripts/lib/fixture.sh"
fixture_repo --with-scripts log-handback.sh,trace-lib.sh,render-action-log.sh
TMP_DIR="$FIXTURE_TMP_DIR"

fail() {
  printf 'FAIL: %s\n' "$*" >&2
  exit 1
}

command -v jq >/dev/null 2>&1 \
  || fail "jq is required to validate log-handback span emission"

[ -f "$CONTRACT" ] \
  || fail "trace schema contract not found at docs/evaluation/trace-schema.v1.json (${CONTRACT})"

[ -f "$LIB" ] \
  || fail "scripts/trace-lib.sh not found (${LIB}) — prerequisite emitter from issue #93 missing"

[ -f "$RENDERER" ] \
  || fail "scripts/render-action-log.sh not found (${RENDERER}) — renderer from issue #332 missing"

# RED gate: the helper under test must exist before anything can run.
[ -f "$HELPER" ] \
  || fail "scripts/log-handback.sh not found (${HELPER}) — the single-source handback helper for feature log-handback-helper (issue #95) is not implemented yet"

# --- Contract-driven span validation ------------------------------------------
# ============================================================================
# TRACE SPAN VALIDATION FILTER (self-contained; issue #97 lifts this unchanged)
# Usage: jq -e --slurpfile contract docs/evaluation/trace-schema.v1.json \
#            -f validate-span.jq  <<< "$one_span_json_line"
# A span line is valid iff the filter outputs true (jq -e exit 0). A non-JSON
# line fails jq parsing itself (non-zero exit), which is also a rejection.
# ============================================================================
FILTER="${TMP_DIR}/validate-span.jq"
cat > "$FILTER" <<'JQ'
$contract[0] as $c
| . as $span
| (($span | type) == "object")
  and ((($c.required_common // []) - ($span | keys)) | length == 0)
  and (($c.span_types // []) | index($span.span) != null)
  and (((($c.required_by_span // {})[$span.span // ""] // []) - ($span | keys)) | length == 0)
  and (if $span.span == "lifecycle"
       then (($c.lifecycle_steps // []) | index($span["harness.lifecycle_step"]) != null)
       else true
       end)
JQ

validate_span() {
  printf '%s\n' "$1" \
    | jq -e --slurpfile contract "$CONTRACT" -f "$FILTER" >/dev/null 2>&1
}

# --- Helpers -------------------------------------------------------------------
line_count() { wc -l < "$1" | tr -d '[:space:]'; }
nth_line() { sed -n "${2}p" "$1"; }

link_tools() {
  local dir="$1"; shift
  mkdir -p "$dir"
  local t p
  for t in "$@"; do
    p="$(command -v "$t" || true)"
    [ -n "$p" ] && ln -sf "$p" "${dir}/${t}"
  done
}

# check_agent_span <label> <line> <role> <step> <feature_id> <outcome> <summary> <issue>
check_agent_span() {
  local label="$1" line="$2" role="$3" step="$4" fid="$5" outcome="$6" summary="$7" issue="$8"
  validate_span "$line" \
    || fail "${label}: span rejected by the contract-driven jq validation filter (#92): ${line}"
  printf '%s\n' "$line" | jq -e \
    --arg role "$role" --arg step "$step" --arg fid "$fid" \
    --arg outcome "$outcome" --arg summary "$summary" --argjson issue "$issue" '
      (.span == "agent")
      and (.["gen_ai.operation.name"] == "invoke_agent")
      and (.["gen_ai.agent.name"] == $role)
      and (.["harness.lifecycle_step"] == $step)
      and (.["harness.feature_id"] == $fid)
      and (.["harness.outcome"] == $outcome)
      and (.["harness.summary"] == $summary)
      and ((.["harness.issue"] | type) == "number")
      and (.["harness.issue"] == $issue)
    ' >/dev/null \
    || fail "${label}: agent span must carry gen_ai.operation.name=invoke_agent, gen_ai.agent.name=${role}, harness.lifecycle_step=${step}, harness.feature_id=${fid}, harness.outcome=${outcome}, harness.summary='${summary}', numeric harness.issue=${issue}: ${line}"
}

# expect_bullet <label> <progress-file> <bullet-line>
# The bullet must exist exactly once, verbatim (D3 format), positioned AFTER
# the '## Action Log' heading.
expect_bullet() {
  local label="$1" file="$2" bullet="$3" hits al_ln b_ln
  hits="$(grep -cF -- "$bullet" "$file" || true)"
  [ "$hits" = "1" ] \
    || fail "${label}: expected exactly one verbatim Action Log bullet '${bullet}' in ${file}, found ${hits}"
  al_ln="$(grep -n '^## Action Log' "$file" | head -1 | cut -d: -f1)"
  [ -n "$al_ln" ] || fail "${label}: fixture progress.md lost its '## Action Log' heading"
  b_ln="$(grep -nF -- "$bullet" "$file" | head -1 | cut -d: -f1)"
  [ "$b_ln" -gt "$al_ln" ] \
    || fail "${label}: the Action Log bullet must be appended UNDER the '## Action Log' heading (heading line ${al_ln}, bullet line ${b_ln})"
}

# Pinned PATH for the scripts under test (real tools, no gh needed).
BIN="${TMP_DIR}/bin"
link_tools "$BIN" bash sh env git basename dirname mkdir rm cp mv cat sed awk tr cut grep printf head tail sort jq date od wc cksum stat chmod mktemp

unset TRACE_ISSUE TRACE_PARENT_SPAN_ID TRACE_INPUT_TOKENS TRACE_OUTPUT_TOKENS \
  TRACE_FAILURE_MODE TRACE_INSTRUCTION_FILES TRACE_REVIEW_MODE 2>/dev/null || true

# --- Fixture: MAIN repo + linked issue worktrees ---------------------------------
MAIN="$FIXTURE_REPO"

# scaffold_progress <worktree> <NN>: minimal start-issue.sh-shaped progress.md
# with an '## Action Log' section, in the WORKTREE's tracking dir.
scaffold_progress() {
  local wt="$1" nn="$2"
  mkdir -p "${wt}/.copilot-tracking/issues/issue-${nn}"
  cat > "${wt}/.copilot-tracking/issues/issue-${nn}/progress.md" <<MD
# Issue ${nn} progress

Status: in progress.

## Action Log

- _Record conductor handbacks, subagent actions, review verdicts, and recovery notes here._
MD
}

# Worktree A (issue 13): the happy-path conductor context.
WTA="${TMP_DIR}/wt-issue-13"
git -C "$MAIN" worktree add -q -b feature/issue-13-fixture "$WTA"
scaffold_progress "$WTA" 13
TRACE_A="${MAIN}/.copilot-tracking/issues/issue-13/trace.jsonl"
PROG_A="${WTA}/.copilot-tracking/issues/issue-13/progress.md"

run_hb() { # run_hb <worktree> <out-file> <args...>  (stdout+stderr combined)
  local wt="$1" out="$2"; shift 2
  (cd "$wt" && PATH="$BIN" ./scripts/log-handback.sh "$@") > "$out" 2>&1
}

# ============================================================================
# 1. Happy path: one call → one agent span (MAIN root); renderer populates
#    the Action Log section of the WORKTREE progress.md.
#    Variadic summary args are space-joined.
# ============================================================================
SUMMARY1="RED sensor authored; fails for the right reason"
run_hb "$WTA" "${TMP_DIR}/a1.out" \
  generator-subagent red_handback log-handback-helper pass \
  "RED sensor authored;" "fails for the right reason" \
  || { cat "${TMP_DIR}/a1.out"; fail "happy-path handback call must exit 0"; }
[ -f "$TRACE_A" ] \
  || fail "happy path: no span emitted — main-root trace file missing (${TRACE_A})"
[ "$(line_count "$TRACE_A")" = "1" ] \
  || fail "happy path: expected exactly 1 agent span, got $(line_count "$TRACE_A")"
a1="$(nth_line "$TRACE_A" 1)"
check_agent_span "happy path" "$a1" generator-subagent red_handback log-handback-helper pass "$SUMMARY1" 13
printf '%s\n' "$a1" | jq -e '
    (has("gen_ai.usage.input_tokens") | not)
    and (has("gen_ai.usage.output_tokens") | not)
  ' >/dev/null \
  || fail "happy path: token env unset → gen_ai.usage.* keys must be ABSENT (omit, never fake): ${a1}"

# Span lands at the MAIN root, never inside the worktree (trace-lib D1).
[ ! -e "${WTA}/.copilot-tracking/issues/issue-13/trace.jsonl" ] \
  || fail "spans from the worktree must land at the MAIN root, not ${WTA}/.copilot-tracking"

# Renderer updates the worktree progress.md Action Log section from the span.
BULLET1="- [generator-subagent] red_handback log-handback-helper pass — ${SUMMARY1}"
expect_bullet "happy path" "$PROG_A" "$BULLET1"

# Single-source: the span's harness.summary is reproduced verbatim in the
# rendered Action Log line (renderer reads it from trace.jsonl).
span_summary="$(printf '%s\n' "$a1" | jq -r '.["harness.summary"]')"
grep -qF -- "$span_summary" "$PROG_A" \
  || fail "single-source: the span's harness.summary ('${span_summary}') must appear verbatim in the rendered progress.md Action Log line"

# ============================================================================
# 2. Token passthrough (pinned convention: env vars) → JSON numbers.
# ============================================================================
run_hb2() { # like run_hb but with the token env exported
  local wt="$1" out="$2" itok="$3" otok="$4"; shift 4
  (cd "$wt" && TRACE_INPUT_TOKENS="$itok" TRACE_OUTPUT_TOKENS="$otok" \
     PATH="$BIN" ./scripts/log-handback.sh "$@") > "$out" 2>&1
}
run_hb2 "$WTA" "${TMP_DIR}/a2.out" 1234 56 \
  conductor feature_start log-handback-helper pass "selected next passes:false feature" \
  || { cat "${TMP_DIR}/a2.out"; fail "handback with token env must exit 0"; }
[ "$(line_count "$TRACE_A")" = "2" ] || fail "token call must append exactly one span"
a2="$(nth_line "$TRACE_A" 2)"
check_agent_span "tokens" "$a2" conductor feature_start log-handback-helper pass \
  "selected next passes:false feature" 13
printf '%s\n' "$a2" | jq -e '
    ((.["gen_ai.usage.input_tokens"] | type) == "number")
    and (.["gen_ai.usage.input_tokens"] == 1234)
    and ((.["gen_ai.usage.output_tokens"] | type) == "number")
    and (.["gen_ai.usage.output_tokens"] == 56)
  ' >/dev/null \
  || fail "TRACE_INPUT_TOKENS/TRACE_OUTPUT_TOKENS must land as JSON numbers 1234/56: ${a2}"

# Non-numeric token env → omit, never fake (call still succeeds, keys absent).
run_hb2 "$WTA" "${TMP_DIR}/a3.out" "lots" "" \
  conductor plan_handback - pass "plan approved at the human gate" \
  || { cat "${TMP_DIR}/a3.out"; fail "non-numeric token env must not fail the call (omit, never fake)"; }
[ "$(line_count "$TRACE_A")" = "3" ] || fail "non-numeric-token call must still append exactly one span"
a3="$(nth_line "$TRACE_A" 3)"
printf '%s\n' "$a3" | jq -e '
    (has("gen_ai.usage.input_tokens") | not)
    and (has("gen_ai.usage.output_tokens") | not)
  ' >/dev/null \
  || fail "non-numeric/empty token env must OMIT gen_ai.usage.* (never fake, never stringify): ${a3}"

# ============================================================================
# 3. Deviation: step=deviation with feature_id='-' and outcome=blocked.
# ============================================================================
run_hb "$WTA" "${TMP_DIR}/a4.out" \
  conductor deviation - blocked "stop/report: sensor conflicts with contract" \
  || { cat "${TMP_DIR}/a4.out"; fail "deviation handback (feature_id='-', outcome=blocked) must exit 0"; }
[ "$(line_count "$TRACE_A")" = "4" ] || fail "deviation call must append exactly one span"
a4="$(nth_line "$TRACE_A" 4)"
check_agent_span "deviation" "$a4" conductor deviation - blocked \
  "stop/report: sensor conflicts with contract" 13
expect_bullet "deviation" "$PROG_A" \
  "- [conductor] deviation - blocked — stop/report: sensor conflicts with contract"

# ============================================================================
# 4. Redaction: a planted synthetic ghp_ token is masked in BOTH artifacts.
# ============================================================================
GHP="ghp_FAKE0FIXTURE0SECRET0TOKEN0ABCDEFGH"
run_hb "$WTA" "${TMP_DIR}/a5.out" \
  test-subagent green_handback log-handback-helper pass "rotated ${GHP} credential" \
  || { cat "${TMP_DIR}/a5.out"; fail "handback with a secret-shaped summary must still exit 0"; }
[ "$(line_count "$TRACE_A")" = "5" ] || fail "redaction call must append exactly one span"
a5="$(nth_line "$TRACE_A" 5)"
printf '%s' "$a5" | grep -qF -- "$GHP" \
  && fail "SPAN must not carry the raw ghp_ token (trace-lib redaction bypassed): ${a5}"
printf '%s\n' "$a5" | jq -e '.["harness.summary"] | contains("[REDACTED]")' >/dev/null \
  || fail "span harness.summary must carry [REDACTED] in place of the ghp_ token: ${a5}"
grep -qF -- "$GHP" "$PROG_A" \
  && fail "progress.md Action Log line must not carry the raw ghp_ token (rendered from already-redacted trace)"
grep -q 'green_handback.*\[REDACTED\]' "$PROG_A" \
  || fail "rendered progress.md green_handback line must carry [REDACTED] in place of the ghp_ token"

# ============================================================================
# 5. Closed-enum validation: bad step / role / outcome and missing args →
#    non-zero exit, NO span, NO log line (nothing written).
# ============================================================================
prog_sum_before="$(cksum "$PROG_A")"

if run_hb "$WTA" "${TMP_DIR}/a6.out" test-subagent banana log-handback-helper pass "oops"; then
  cat "${TMP_DIR}/a6.out"; fail "out-of-vocabulary lifecycle step 'banana' must hard-fail (non-zero exit)"
fi
if run_hb "$WTA" "${TMP_DIR}/a7.out" intern red_handback log-handback-helper pass "oops"; then
  cat "${TMP_DIR}/a7.out"; fail "unknown role 'intern' must hard-fail (closed role enum)"
fi
if run_hb "$WTA" "${TMP_DIR}/a8.out" conductor review_verdict log-handback-helper maybe "oops"; then
  cat "${TMP_DIR}/a8.out"; fail "unknown outcome 'maybe' must hard-fail (pass|fail|blocked only)"
fi
if run_hb "$WTA" "${TMP_DIR}/a9.out" conductor feature_start log-handback-helper; then
  cat "${TMP_DIR}/a9.out"; fail "missing outcome/summary args must hard-fail (usage error)"
fi
# feature_id shape (loop-2 hardening): a single [A-Za-z0-9._-]+ token only —
# whitespace or ']' would corrupt the '- [role] step id outcome — summary'
# bullet shape and the span/log tuple parsing.
if run_hb "$WTA" "${TMP_DIR}/a10.out" conductor feature_start "two words" pass "oops"; then
  cat "${TMP_DIR}/a10.out"; fail "feature_id containing a space must hard-fail (single-token shape)"
fi
if run_hb "$WTA" "${TMP_DIR}/a11.out" conductor feature_start "bad]id" pass "oops"; then
  cat "${TMP_DIR}/a11.out"; fail "feature_id containing ']' must hard-fail (would corrupt the bullet shape)"
fi

[ "$(line_count "$TRACE_A")" = "5" ] \
  || fail "validation failures must write NO span (expected 5 lines, got $(line_count "$TRACE_A"))"
[ "$(cksum "$PROG_A")" = "$prog_sum_before" ] \
  || fail "validation failures must write NO Action Log line (progress.md changed)"

# ============================================================================
# 5b. Newline-containing summary (loop-2 hardening): flattened to spaces —
#     ONE span and ONE single-line rendered bullet, identical flattened text.
# ============================================================================
run_hb "$WTA" "${TMP_DIR}/a12.out" \
  implementation-subagent impl_handback log-handback-helper pass \
  $'first line\nsecond line' \
  || { cat "${TMP_DIR}/a12.out"; fail "newline-containing summary must still exit 0 (flattened, not rejected)"; }
[ "$(line_count "$TRACE_A")" = "6" ] \
  || fail "newline-summary call must append exactly one span (got $(line_count "$TRACE_A") lines)"
a12="$(nth_line "$TRACE_A" 6)"
check_agent_span "newline-flatten" "$a12" implementation-subagent impl_handback \
  log-handback-helper pass "first line second line" 13
expect_bullet "newline-flatten" "$PROG_A" \
  "- [implementation-subagent] impl_handback log-handback-helper pass — first line second line"

# ============================================================================
# 6. progress.md MISSING: span IS written; renderer warns (warn-never-fail)
#    and does not create progress.md; log-handback exits 0.
#    (Old behavior was a hard-fail with orphan-span warning; that is retired.)
# ============================================================================
WTB="${TMP_DIR}/wt-issue-14"
git -C "$MAIN" worktree add -q -b feature/issue-14-noprogress "$WTB"
TRACE_B="${MAIN}/.copilot-tracking/issues/issue-14/trace.jsonl"

run_hb "$WTB" "${TMP_DIR}/b1.out" conductor impl_handback some-feature pass "impl done" \
  || { cat "${TMP_DIR}/b1.out"; fail "missing progress.md must NOT hard-fail (renderer is warn-never-fail, exit 0)"; }
[ ! -e "${WTB}/.copilot-tracking/issues/issue-14/progress.md" ] \
  || fail "renderer must NOT create progress.md when it is missing"
if [ ! -f "$TRACE_B" ] || [ "$(line_count "$TRACE_B")" != "1" ]; then
  fail "agent span must be written even when progress.md is missing (expected exactly 1 line in ${TRACE_B})"
fi
check_agent_span "missing-progress" "$(nth_line "$TRACE_B" 1)" conductor impl_handback some-feature pass "impl done" 14
# Renderer must surface its warn-never-fail diagnostic on stderr; suppressing
# it with 2>/dev/null is forbidden — the warn-never-fail contract means the
# warning IS the signal, not a noise to be silenced.
grep -qi 'render-action-log' "${TMP_DIR}/b1.out" \
  || { cat "${TMP_DIR}/b1.out"; fail "missing-progress: renderer warn-never-fail diagnostic must appear in stderr output (2>/dev/null suppression removed from log-handback.sh renderer call)"; }

# ============================================================================
# 7. progress.md present but NO '## Action Log' section: span IS written;
#    renderer warns (warn-never-fail) and leaves progress.md unchanged;
#    log-handback exits 0.
# ============================================================================
WTC="${TMP_DIR}/wt-issue-15"
git -C "$MAIN" worktree add -q -b feature/issue-15-nosection "$WTC"
mkdir -p "${WTC}/.copilot-tracking/issues/issue-15"
printf '# Issue 15 progress\n\nStatus: garbled scaffold without the log section.\n' \
  > "${WTC}/.copilot-tracking/issues/issue-15/progress.md"
PROG_C="${WTC}/.copilot-tracking/issues/issue-15/progress.md"
TRACE_C="${MAIN}/.copilot-tracking/issues/issue-15/trace.jsonl"
progc_sum_before="$(cksum "$PROG_C")"

TRACE_ACTIONABLE=true TRACE_FINDING_REPRODUCTION=test run_hb "$WTC" "${TMP_DIR}/c1.out" code-review-subagent review_verdict some-feature fail "needs rework" \
  || { cat "${TMP_DIR}/c1.out"; fail "missing '## Action Log' section must NOT hard-fail (renderer is warn-never-fail, exit 0)"; }
[ "$(cksum "$PROG_C")" = "$progc_sum_before" ] \
  || fail "renderer must not modify progress.md when it has no '## Action Log' section"
if [ ! -f "$TRACE_C" ] || [ "$(line_count "$TRACE_C")" != "1" ]; then
  fail "agent span must be written even when progress.md has no '## Action Log' section (expected exactly 1 line in ${TRACE_C})"
fi
# Renderer must surface its warn-never-fail diagnostic on stderr; suppressing
# it with 2>/dev/null is forbidden — the warn-never-fail contract means the
# warning IS the signal, not a noise to be silenced.
grep -qi 'render-action-log' "${TMP_DIR}/c1.out" \
  || { cat "${TMP_DIR}/c1.out"; fail "missing-heading: renderer warn-never-fail diagnostic must appear in stderr output (2>/dev/null suppression removed from log-handback.sh renderer call)"; }

# ============================================================================
# 8. trace-lib.sh ABSENT: tracing degrades (span skipped), renderer called
#    but finds no trace — warns (mentioning trace-lib), exits 0, no trace
#    file created. The Action Log section keeps its existing content;
#    log-handback must NOT directly append a bullet.
# ============================================================================
R2="${TMP_DIR}/r2-nolib"
git clone -q "$MAIN" "$R2"
git -C "$R2" config user.name "Harness Test"
git -C "$R2" config user.email "harness-test@example.invalid"
git -C "$R2" checkout -q -b feature/issue-21-nolib
rm -f "${R2}/scripts/trace-lib.sh" "${R2}/scripts/render-action-log.sh"
git -C "$R2" add scripts
git -C "$R2" commit -q -m "remove trace dependencies"
scaffold_progress "$R2" 21
[ ! -e "${R2}/scripts/trace-lib.sh" ] || fail "fixture bug: R2 must not contain trace-lib.sh"

(cd "$R2" && PATH="$BIN" ./scripts/log-handback.sh \
   planning-subagent plan_handback - pass "plan drafted, two open questions") \
  > "${TMP_DIR}/r2.out" 2>&1 \
  || { cat "${TMP_DIR}/r2.out"; fail "trace-lib absent: the helper must still exit 0 (tracing degrades, span skipped)"; }
grep -qi 'trace-lib' "${TMP_DIR}/r2.out" \
  || { cat "${TMP_DIR}/r2.out"; fail "trace-lib absent: the helper must warn on stderr mentioning trace-lib"; }
[ ! -e "${R2}/.copilot-tracking/issues/issue-21/trace.jsonl" ] \
  || fail "trace-lib absent: no trace file may be created"
# The helper must NOT directly append a bullet — Action Log is rendered-only.
grep -qF "plan_handback" "${R2}/.copilot-tracking/issues/issue-21/progress.md" \
  && fail "trace-lib absent: helper must NOT directly append an Action Log bullet (rendered from trace only)"

# ============================================================================
# 9. Span DROPPED by trace-lib while progress.md is writable (loop-2
#    hardening): trace.jsonl is made unappendable (a directory squats on the
#    path), so trace_span warn-drops. log-handback must still exit 0; the
#    renderer finds the trace path is not a regular file and warns without
#    modifying progress.md. No direct bullet appended.
# ============================================================================
WTD="${TMP_DIR}/wt-issue-16"
git -C "$MAIN" worktree add -q -b feature/issue-16-spandrop "$WTD"
scaffold_progress "$WTD" 16
mkdir -p "${MAIN}/.copilot-tracking/issues/issue-16/trace.jsonl"
[ -d "${MAIN}/.copilot-tracking/issues/issue-16/trace.jsonl" ] \
  || fail "fixture bug: issue-16 trace.jsonl must be a directory (unappendable)"

run_hb "$WTD" "${TMP_DIR}/d1.out" \
  test-subagent green_handback log-handback-helper pass "verified with dropped span" \
  || { cat "${TMP_DIR}/d1.out"; fail "span-drop path must exit 0"; }
[ -d "${MAIN}/.copilot-tracking/issues/issue-16/trace.jsonl" ] \
  || fail "span-drop fixture: the unappendable trace.jsonl directory must be untouched"
# No direct bullet appended when span is dropped — renderer-based only.
grep -qF "green_handback" "${WTD}/.copilot-tracking/issues/issue-16/progress.md" \
  && fail "span-drop: helper must NOT directly append a bullet (rendered from trace only)"

# ============================================================================
# 10. TRACE_FAILURE_MODE passthrough (issue #99, feature
#     failure-mode-span-plumbing). See the pinned convention in the header:
#     enum-valid value → harness.failure_mode lands as a JSON string on the
#     span; unset → key absent; out-of-enum → key omitted + stderr warning,
#     exit 0; attaches on ANY step (soft convention, no step gate); the
#     Action Log bullet format is unchanged.
# ============================================================================
run_hb_fm() { # like run_hb but with TRACE_FAILURE_MODE exported
  local wt="$1" out="$2" mode="$3"; shift 3
  (cd "$wt" && TRACE_FAILURE_MODE="$mode" PATH="$BIN" ./scripts/log-handback.sh "$@") > "$out" 2>&1
}

# 10a. Valid mode on a deviation handback → span carries harness.failure_mode.
run_hb_fm "$WTA" "${TMP_DIR}/f1.out" token-thrash \
  conductor deviation - blocked "same files re-read in a loop, no convergence" \
  || { cat "${TMP_DIR}/f1.out"; fail "deviation handback with TRACE_FAILURE_MODE=token-thrash must exit 0"; }
[ "$(line_count "$TRACE_A")" = "7" ] \
  || fail "failure-mode deviation call must append exactly one span (got $(line_count "$TRACE_A") lines)"
f1="$(nth_line "$TRACE_A" 7)"
check_agent_span "failure-mode deviation" "$f1" conductor deviation - blocked \
  "same files re-read in a loop, no convergence" 13
printf '%s\n' "$f1" | jq -e '.["harness.failure_mode"] == "token-thrash"' >/dev/null \
  || fail "TRACE_FAILURE_MODE=token-thrash on a deviation must land as harness.failure_mode=\"token-thrash\" (JSON string): ${f1}"
expect_bullet "failure-mode deviation" "$PROG_A" \
  "- [conductor] deviation - blocked — same files re-read in a loop, no convergence"

# 10b. Out-of-enum mode → key OMITTED, stderr warning naming the failure
#      mode, call still exits 0 (omit, never fake, never hard-fail).
run_hb_fm "$WTA" "${TMP_DIR}/f2.out" banana \
  conductor deviation - blocked "deviation with a bogus failure mode" \
  || { cat "${TMP_DIR}/f2.out"; fail "out-of-enum TRACE_FAILURE_MODE=banana must NOT fail the call (omit, never fake)"; }
[ "$(line_count "$TRACE_A")" = "8" ] \
  || fail "bogus-failure-mode call must still append exactly one span (got $(line_count "$TRACE_A") lines)"
f2="$(nth_line "$TRACE_A" 8)"
check_agent_span "bogus failure mode" "$f2" conductor deviation - blocked \
  "deviation with a bogus failure mode" 13
printf '%s\n' "$f2" | jq -e 'has("harness.failure_mode") | not' >/dev/null \
  || fail "out-of-enum TRACE_FAILURE_MODE=banana must OMIT harness.failure_mode (never fake, never forward): ${f2}"
grep -qiE 'failure[_ -]mode' "${TMP_DIR}/f2.out" \
  || { cat "${TMP_DIR}/f2.out"; fail "out-of-enum TRACE_FAILURE_MODE must warn on stderr naming the failure mode (silent omit forbidden)"; }

# 10c. Env unset → key absent (control for 10a).
run_hb "$WTA" "${TMP_DIR}/f3.out" \
  conductor deviation - blocked "deviation without a failure mode" \
  || { cat "${TMP_DIR}/f3.out"; fail "deviation handback without TRACE_FAILURE_MODE must exit 0"; }
[ "$(line_count "$TRACE_A")" = "9" ] \
  || fail "no-failure-mode deviation call must append exactly one span (got $(line_count "$TRACE_A") lines)"
f3="$(nth_line "$TRACE_A" 9)"
printf '%s\n' "$f3" | jq -e 'has("harness.failure_mode") | not' >/dev/null \
  || fail "TRACE_FAILURE_MODE unset → harness.failure_mode must be ABSENT: ${f3}"

# 10d. Valid mode on a NON-deviation step attaches too (pinned soft rule:
#      the deviation convention is prose, not a passthrough gate).
run_hb_fm "$WTA" "${TMP_DIR}/f4.out" weak-sensor \
  test-subagent green_handback log-handback-helper pass "green despite a sensor that did not bite" \
  || { cat "${TMP_DIR}/f4.out"; fail "TRACE_FAILURE_MODE on a non-deviation step must not fail the call (soft convention, no step gate)"; }
[ "$(line_count "$TRACE_A")" = "10" ] \
  || fail "non-deviation failure-mode call must append exactly one span (got $(line_count "$TRACE_A") lines)"
f4="$(nth_line "$TRACE_A" 10)"
printf '%s\n' "$f4" | jq -e '.["harness.failure_mode"] == "weak-sensor"' >/dev/null \
  || fail "TRACE_FAILURE_MODE=weak-sensor must attach on ANY step when set (pinned soft rule): ${f4}"

# ============================================================================
# 11. Contract-read enum branch + fallback/contract parity (loop-2 review
#     majors). Sections 10a–10d ran with NO contract file in the fixture, so
#     they only prove the MIRRORED FALLBACK branch. This section pins:
#     11a. the contract-READ branch is live: with a contract present at
#          <script_dir>/../docs/evaluation/trace-schema.v1.json whose
#          failure_modes DIVERGES from the mirrored fallback (a synthetic
#          9th mode), the divergent mode must be accepted — only the jq
#          branch can do that;
#     11b. static parity: the helper's mirrored fallback list must equal the
#          REAL contract's failure_modes exactly (sorted compare), so enum
#          drift between contract and fallback fails a sensor.
# ============================================================================
# 11a. Divergent contract in the worktree (script dir is ${WTA}/scripts, so
#      the helper resolves ${WTA}/docs/evaluation/trace-schema.v1.json).
mkdir -p "${WTA}/docs/evaluation"
jq '.failure_modes += ["test-only-mode"]' "$CONTRACT" \
  > "${WTA}/docs/evaluation/trace-schema.v1.json" \
  || fail "fixture bug: could not derive the divergent 9-mode contract"

run_hb_fm "$WTA" "${TMP_DIR}/f5.out" test-only-mode \
  conductor deviation - blocked "deviation carrying a contract-only mode" \
  || { cat "${TMP_DIR}/f5.out"; fail "TRACE_FAILURE_MODE=test-only-mode with a contract declaring it must exit 0"; }
[ "$(line_count "$TRACE_A")" = "11" ] \
  || fail "contract-branch call must append exactly one span (got $(line_count "$TRACE_A") lines)"
f5="$(nth_line "$TRACE_A" 11)"
printf '%s\n' "$f5" | jq -e '.["harness.failure_mode"] == "test-only-mode"' >/dev/null \
  || fail "contract-READ branch is dead: a mode present ONLY in the contract (test-only-mode) was not forwarded — the helper is deciding from the mirrored fallback even when the contract is readable: ${f5}"
rm -rf "${WTA}/docs"

# 11b. Static parity: extract the mirrored fallback block (the enum='...'
#      literal) from the helper source and compare it, sorted, against the
#      real contract's failure_modes.
fallback_list="$(sed -n "/enum='/,/'/p" "$HELPER" \
  | sed -E "s/^[[:space:]]*enum='//; s/'[[:space:]]*$//" \
  | sed '/^[[:space:]]*$/d')"
[ -n "$fallback_list" ] \
  || fail "could not extract the mirrored fallback enum list (enum='...') from scripts/log-handback.sh — keep the fallback extractable so parity stays sensor-checkable"
contract_modes_sorted="$(jq -r '(.failure_modes // [])[]' "$CONTRACT" | sort)"
fallback_sorted="$(printf '%s\n' "$fallback_list" | sort)"
[ "$fallback_sorted" = "$contract_modes_sorted" ] \
  || fail "mirrored fallback enum in scripts/log-handback.sh differs from the contract's failure_modes — fallback==contract is pinned (fallback: $(printf '%s' "$fallback_list" | tr '\n' ','); contract: $(printf '%s' "$contract_modes_sorted" | tr '\n' ','))"

# ============================================================================
# 12. TRACE_INSTRUCTION_FILES passthrough (issue #300, feature
#     instruction-files-span). Mirrors the token / failure-mode passthrough
#     (see the pinned convention in the header): any non-empty value →
#     harness.instruction_files lands VERBATIM as a JSON string on the span
#     (no enum, no validation — it is a space/comma-separated list of
#     instruction-file paths); unset or empty → the key is ABSENT (omit,
#     never fake). Attaches on ANY step; the Action Log bullet is unchanged.
# ============================================================================
run_hb_if() { # like run_hb but with TRACE_INSTRUCTION_FILES exported
  local wt="$1" out="$2" files="$3"; shift 3
  (cd "$wt" && TRACE_INSTRUCTION_FILES="$files" PATH="$BIN" ./scripts/log-handback.sh "$@") > "$out" 2>&1
}
IF_FILES=".copilot/instructions/bash.instructions.md .copilot/instructions/tdd.instructions.md"

# 12a. Non-empty value → span carries harness.instruction_files verbatim.
run_hb_if "$WTA" "${TMP_DIR}/g1.out" "$IF_FILES" \
  generator-subagent red_handback instruction-files-span pass "RED sensor authored under two instruction files" \
  || { cat "${TMP_DIR}/g1.out"; fail "handback with TRACE_INSTRUCTION_FILES set must exit 0"; }
[ "$(line_count "$TRACE_A")" = "12" ] \
  || fail "instruction-files call must append exactly one span (got $(line_count "$TRACE_A") lines)"
g1="$(nth_line "$TRACE_A" 12)"
check_agent_span "instruction-files" "$g1" generator-subagent red_handback \
  instruction-files-span pass "RED sensor authored under two instruction files" 13
printf '%s\n' "$g1" | jq -e --arg files "$IF_FILES" \
  '.["harness.instruction_files"] == $files' >/dev/null \
  || fail "TRACE_INSTRUCTION_FILES must land VERBATIM as harness.instruction_files (JSON string): ${g1}"

# 12b. Env unset → key ABSENT (omit, never fake — control for 12a).
run_hb "$WTA" "${TMP_DIR}/g2.out" \
  generator-subagent green_handback instruction-files-span pass "green without an instruction-files env" \
  || { cat "${TMP_DIR}/g2.out"; fail "handback without TRACE_INSTRUCTION_FILES must exit 0"; }
[ "$(line_count "$TRACE_A")" = "13" ] \
  || fail "no-instruction-files call must append exactly one span (got $(line_count "$TRACE_A") lines)"
g2="$(nth_line "$TRACE_A" 13)"
printf '%s\n' "$g2" | jq -e 'has("harness.instruction_files") | not' >/dev/null \
  || fail "TRACE_INSTRUCTION_FILES unset → harness.instruction_files must be ABSENT: ${g2}"

# 12c. Empty value → key ABSENT (empty is not forwarded — omit, never fake).
run_hb_if "$WTA" "${TMP_DIR}/g3.out" "" \
  generator-subagent impl_handback instruction-files-span pass "empty instruction-files env is omitted" \
  || { cat "${TMP_DIR}/g3.out"; fail "empty TRACE_INSTRUCTION_FILES must not fail the call (omit, never fake)"; }
[ "$(line_count "$TRACE_A")" = "14" ] \
  || fail "empty-instruction-files call must still append exactly one span (got $(line_count "$TRACE_A") lines)"
g3="$(nth_line "$TRACE_A" 14)"
printf '%s\n' "$g3" | jq -e 'has("harness.instruction_files") | not' >/dev/null \
  || fail "empty TRACE_INSTRUCTION_FILES must OMIT harness.instruction_files (never fake, never emit empty): ${g3}"

# ============================================================================
# 13. TRACE_REVIEW_MODE + auto-captured reviewed_sha (issue #299, feature
#     review-verdict-provenance). BOTH attrs are scoped to the review_verdict
#     step ONLY:
#       TRACE_REVIEW_MODE  → harness.review_mode  (JSON string, CLOSED enum
#                            {full, concise, repair}; out-of-enum / empty →
#                            key OMITTED + stderr warning, exit 0 — omit,
#                            never fake, mirroring the failure-mode shape).
#       harness.reviewed_sha → AUTO-captured at emit time from `git rev-parse
#                            HEAD` (NOT any env var); omitted when unresolvable.
#     On EVERY non-review_verdict step both attrs are ABSENT even when
#     TRACE_REVIEW_MODE is set in the ambient env (guarded on the step).
# ============================================================================
run_hb_rm() { # like run_hb but with TRACE_REVIEW_MODE exported
  local wt="$1" out="$2" mode="$3"; shift 3
  (cd "$wt" && TRACE_REVIEW_MODE="$mode" PATH="$BIN" ./scripts/log-handback.sh "$@") > "$out" 2>&1
}
# The worktree's current HEAD — what the helper must auto-capture.
WT_HEAD="$(git -C "$WTA" rev-parse HEAD)"
[ -n "$WT_HEAD" ] || fail "fixture bug: could not resolve the worktree HEAD to compare reviewed_sha against"

# 13a. review_verdict + TRACE_REVIEW_MODE=full → span carries
#      harness.review_mode="full" AND harness.reviewed_sha=<worktree HEAD>.
run_hb_rm "$WTA" "${TMP_DIR}/h1.out" full \
  code-review-subagent review_verdict review-verdict-provenance pass "APPROVE: sensor bites, product-quality met" \
  || { cat "${TMP_DIR}/h1.out"; fail "review_verdict handback with TRACE_REVIEW_MODE=full must exit 0"; }
[ "$(line_count "$TRACE_A")" = "15" ] \
  || fail "review-mode call must append exactly one span (got $(line_count "$TRACE_A") lines)"
h1="$(nth_line "$TRACE_A" 15)"
check_agent_span "review-mode full" "$h1" code-review-subagent review_verdict \
  review-verdict-provenance pass "APPROVE: sensor bites, product-quality met" 13
printf '%s\n' "$h1" | jq -e --arg sha "$WT_HEAD" '
    (.["harness.review_mode"] == "full")
    and (.["harness.reviewed_sha"] == $sha)
  ' >/dev/null \
  || fail "review_verdict + TRACE_REVIEW_MODE=full must carry harness.review_mode=\"full\" AND auto-captured harness.reviewed_sha=\"${WT_HEAD}\": ${h1}"

# 13b. review_verdict + TRACE_REVIEW_MODE UNSET → harness.review_mode ABSENT,
#      but harness.reviewed_sha STILL present (auto-captured, not env-driven).
TRACE_ACTIONABLE=true TRACE_FINDING_REPRODUCTION=test run_hb "$WTA" "${TMP_DIR}/h2.out" \
  code-review-subagent review_verdict review-verdict-provenance fail "NEEDS_REVISION: missing negative fixture" \
  || { cat "${TMP_DIR}/h2.out"; fail "review_verdict handback without TRACE_REVIEW_MODE must exit 0"; }
[ "$(line_count "$TRACE_A")" = "16" ] \
  || fail "no-review-mode call must append exactly one span (got $(line_count "$TRACE_A") lines)"
h2="$(nth_line "$TRACE_A" 16)"
printf '%s\n' "$h2" | jq -e --arg sha "$WT_HEAD" '
    (has("harness.review_mode") | not)
    and (.["harness.reviewed_sha"] == $sha)
  ' >/dev/null \
  || fail "review_verdict without TRACE_REVIEW_MODE must OMIT harness.review_mode but STILL carry auto-captured harness.reviewed_sha=\"${WT_HEAD}\": ${h2}"

# 13c. review_verdict + TRACE_REVIEW_MODE=bogus → harness.review_mode OMITTED
#      + stderr warning, exit 0 (out-of-enum → omit, never fake).
run_hb_rm "$WTA" "${TMP_DIR}/h3.out" bogus \
  code-review-subagent review_verdict review-verdict-provenance pass "review carrying a bogus mode" \
  || { cat "${TMP_DIR}/h3.out"; fail "out-of-enum TRACE_REVIEW_MODE=bogus must NOT fail the call (omit, never fake)"; }
[ "$(line_count "$TRACE_A")" = "17" ] \
  || fail "bogus-review-mode call must still append exactly one span (got $(line_count "$TRACE_A") lines)"
h3="$(nth_line "$TRACE_A" 17)"
printf '%s\n' "$h3" | jq -e 'has("harness.review_mode") | not' >/dev/null \
  || fail "out-of-enum TRACE_REVIEW_MODE=bogus must OMIT harness.review_mode (never fake, never forward): ${h3}"
grep -qiE 'review[_ -]mode' "${TMP_DIR}/h3.out" \
  || { cat "${TMP_DIR}/h3.out"; fail "out-of-enum TRACE_REVIEW_MODE must warn on stderr naming the review mode (silent omit forbidden)"; }

# 13d. NON-review_verdict step + TRACE_REVIEW_MODE=full → BOTH attrs ABSENT
#      (scoped to review_verdict only, even when the ambient env is set).
run_hb_rm "$WTA" "${TMP_DIR}/h4.out" full \
  generator-subagent impl_handback review-verdict-provenance pass "impl on a non-review step" \
  || { cat "${TMP_DIR}/h4.out"; fail "impl_handback with TRACE_REVIEW_MODE=full must exit 0"; }
[ "$(line_count "$TRACE_A")" = "18" ] \
  || fail "non-review step call must append exactly one span (got $(line_count "$TRACE_A") lines)"
h4="$(nth_line "$TRACE_A" 18)"
printf '%s\n' "$h4" | jq -e '
    (has("harness.review_mode") | not)
    and (has("harness.reviewed_sha") | not)
  ' >/dev/null \
  || fail "non-review_verdict step must OMIT BOTH harness.review_mode and harness.reviewed_sha even when TRACE_REVIEW_MODE is set (scoped to review_verdict): ${h4}"

printf 'log-handback renderer-based handback contract honored\n'

(
cd "$ROOT"

HELPER="${ROOT}/scripts/log-handback.sh"
LIB="${ROOT}/scripts/trace-lib.sh"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

fail() {
  printf 'FAIL: %s\n' "$*" >&2
  exit 1
}

command -v jq >/dev/null 2>&1 || fail "jq is required"
[ -f "$HELPER" ] || fail "scripts/log-handback.sh not found"
[ -f "$LIB" ] || fail "scripts/trace-lib.sh not found"

unset TRACE_ISSUE TRACE_PARENT_SPAN_ID TRACE_SENSOR_SCOPE TRACE_SENSOR_COUNT 2>/dev/null || true

TEMPLATE_REPO="$FIXTURE_REPO"
MAIN="${TMP_DIR}/main-repo"
git clone -q "$TEMPLATE_REPO" "$MAIN"
git -C "$MAIN" remote remove origin
git -C "$MAIN" checkout -q -B main
git -C "$MAIN" config user.name "Harness Test"
git -C "$MAIN" config user.email "harness-test@example.invalid"

WT="${TMP_DIR}/wt-issue-21"
git -C "$MAIN" worktree add -q -b feature/issue-21-fixture "$WT"
mkdir -p "${WT}/.copilot-tracking/issues/issue-21"
cat > "${WT}/.copilot-tracking/issues/issue-21/progress.md" <<'MD'
# Issue 21 progress

## Action Log

- _seed_
MD
TRACE="${MAIN}/.copilot-tracking/issues/issue-21/trace.jsonl"

run_hb() { # run_hb <out-file> [ENV=val ...] -- <helper args...>
  local out="$1"; shift
  local envs=()
  while [ "$1" != "--" ]; do envs+=("$1"); shift; done
  shift
  (cd "$WT" && env "${envs[@]}" ./scripts/log-handback.sh "$@") > "$out" 2>&1
}

last_span() { tail -1 "$TRACE"; }

# 1. Happy path: scoped + count land as harness.sensor_scope / sensor_count.
run_hb "${TMP_DIR}/o1" TRACE_SENSOR_SCOPE=scoped TRACE_SENSOR_COUNT=12 -- \
  generator-subagent green_handback f1 pass "scoped sensor tier ran" \
  || fail "happy path exited non-zero: $(cat "${TMP_DIR}/o1")"
last_span | jq -e '
    (.["harness.sensor_scope"] == "scoped")
    and ((.["harness.sensor_count"] | tostring) == "12")
  ' >/dev/null \
  || fail "green_handback span must carry harness.sensor_scope=scoped and harness.sensor_count=12: $(last_span)"

# 2. full is the other enum member.
run_hb "${TMP_DIR}/o2" TRACE_SENSOR_SCOPE=full -- \
  generator-subagent green_handback f2 pass "full suite ran" \
  || fail "full-scope call exited non-zero"
last_span | jq -e '.["harness.sensor_scope"] == "full"' >/dev/null \
  || fail "harness.sensor_scope=full must be forwarded: $(last_span)"
last_span | jq -e 'has("harness.sensor_count") | not' >/dev/null \
  || fail "sensor_count unset must leave harness.sensor_count absent (independent forwarding)"

# 3. Out-of-enum scope → key omitted, warn, still exit 0, span still written.
before="$(wc -l < "$TRACE" | tr -d '[:space:]')"
run_hb "${TMP_DIR}/o3" TRACE_SENSOR_SCOPE=partial TRACE_SENSOR_COUNT=5 -- \
  generator-subagent green_handback f3 pass "bad scope value" \
  || fail "out-of-enum scope must not fail the call: $(cat "${TMP_DIR}/o3")"
after="$(wc -l < "$TRACE" | tr -d '[:space:]')"
[ "$after" -gt "$before" ] || fail "span must still be written on out-of-enum scope"
last_span | jq -e 'has("harness.sensor_scope") | not' >/dev/null \
  || fail "out-of-enum scope must omit harness.sensor_scope (omit, never fake): $(last_span)"
last_span | jq -e '(.["harness.sensor_count"] | tostring) == "5"' >/dev/null \
  || fail "valid count must still be forwarded when scope is invalid (independent forwarding)"
grep -qi 'sensor_scope' "${TMP_DIR}/o3" \
  || fail "out-of-enum scope must warn naming sensor_scope"

# 4. Non-integer count → key omitted, warn, exit 0.
run_hb "${TMP_DIR}/o4" TRACE_SENSOR_SCOPE=scoped TRACE_SENSOR_COUNT=dozen -- \
  generator-subagent green_handback f4 pass "bad count value" \
  || fail "non-integer count must not fail the call"
last_span | jq -e 'has("harness.sensor_count") | not' >/dev/null \
  || fail "non-integer count must omit harness.sensor_count: $(last_span)"
grep -qi 'sensor_count\|SENSOR_COUNT' "${TMP_DIR}/o4" \
  || fail "non-integer count must warn on stderr"

# 5. Both unset → both keys absent.
run_hb "${TMP_DIR}/o5" HOME="$HOME" -- \
  generator-subagent green_handback f5 pass "no sensor scope env" \
  || fail "unset env call exited non-zero"
last_span | jq -e '(has("harness.sensor_scope") or has("harness.sensor_count")) | not' >/dev/null \
  || fail "unset env must leave both keys absent: $(last_span)"

printf 'PASS: log-handback sensor-scope passthrough honors the #343 contract\n'
)

(
cd "$ROOT"

RENDERER="${ROOT}/scripts/render-action-log.sh"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

fail() { printf 'FAIL: %s\n' "$*" >&2; exit 1; }
command -v jq >/dev/null 2>&1 || fail "jq is required to run render-action-log tests"
[ -f "$RENDERER" ] || fail "scripts/render-action-log.sh not found (${RENDERER}) — the Action Log renderer for feature render-action-log (issue #332) is not implemented yet"

# scaffold_progress <dir>: minimal progress.md with ## Action Log + placeholder.
scaffold_progress() { printf '# Issue fixture\n## Action Log\n- _Record conductor handbacks, subagent actions, review verdicts, and recovery notes here._\n' > "${1}/progress.md"; }

# make_spans <file>: two agent spans (conductor + generator-subagent).
# shellcheck disable=SC1004
make_spans() { printf '%s\n%s\n' \
  '{"schema_version":1,"span":"agent","span_id":"a1","timestamp":"2026-07-01T00:00:00Z","gen_ai.operation.name":"invoke_agent","gen_ai.agent.name":"conductor","harness.lifecycle_step":"feature_start","harness.feature_id":"render-action-log","harness.outcome":"pass","harness.summary":"selected renderer feature","harness.issue":332}' \
  '{"schema_version":1,"span":"agent","span_id":"a2","timestamp":"2026-07-01T00:00:01Z","gen_ai.operation.name":"invoke_agent","gen_ai.agent.name":"generator-subagent","harness.lifecycle_step":"red_handback","harness.feature_id":"render-action-log","harness.outcome":"pass","harness.summary":"RED confirmed for right reason","harness.issue":332}' \
  > "$1"; }

# assert_noop <label> <prog> <trace-arg> <stderr-pat>: exit 0, prog unchanged, stderr matches.
assert_noop() {
  local label="$1" prog="$2" arg="$3" pat="$4" before rc stderr
  before="$(cat "$prog")"; rc=0; stderr="$(bash "$RENDERER" "$arg" 2>&1)" || rc=$?
  [ "$rc" -eq 0 ] || fail "${label}: must exit 0 (warn-never-fail); got ${rc}"
  [ "$(cat "$prog")" = "$before" ] || fail "${label}: progress.md must be unchanged"
  printf '%s\n' "$stderr" | grep -qi "$pat" || fail "${label}: must warn to stderr"
}
# assert_noop_path: like assert_noop with PATH override for fakebin dir ($5).
assert_noop_path() {
  local label="$1" prog="$2" trace="$3" pat="$4" fb="$5" before rc stderr
  before="$(cat "$prog")"; rc=0; stderr="$(PATH="${fb}:${PATH}" bash "$RENDERER" "$trace" 2>&1)" || rc=$?
  [ "$rc" -eq 0 ] || fail "${label}: must exit 0 (warn-never-fail); got ${rc}"
  [ "$(cat "$prog")" = "$before" ] || fail "${label}: progress.md must be unchanged"
  printf '%s\n' "$stderr" | grep -qi "$pat" || fail "${label}: must warn to stderr"
}
# fakebin <dir> <cmd> <body>: write executable fakebin script.
fakebin() { printf '#!/usr/bin/env bash\n%s\n' "$3" > "${1}/${2}"; chmod +x "${1}/${2}"; }
# git_repo <dir>: clone the shared committed fixture.
git_repo() {
  rm -rf "$1"
  git clone -q "$FIXTURE_REPO" "$1"
  git -C "$1" remote remove origin
  git -C "$1" checkout -q -B main
  git -C "$1" config user.name T
  git -C "$1" config user.email t@t.t
}

# --- Leg 1: two agent spans → bullets under ## Action Log (path mode) ---
d="${TMP_DIR}/l1"; mkdir -p "$d"; make_spans "${d}/trace.jsonl"; scaffold_progress "$d"
rc=0; bash "$RENDERER" "${d}/trace.jsonl" 2>/dev/null || rc=$?
[ "$rc" -eq 0 ] || fail "leg1: exit 0"
grep -q -- '^## Action Log$' "${d}/progress.md" || fail "leg1: heading survives"
grep -qF -- '- [conductor] feature_start render-action-log pass — selected renderer feature' "${d}/progress.md" || fail "leg1: first span bullet"
grep -qF -- '- [generator-subagent] red_handback render-action-log pass — RED confirmed for right reason' "${d}/progress.md" || fail "leg1: second span bullet"
al="$(grep -n '^## Action Log$' "${d}/progress.md" | head -1 | cut -d: -f1)"
[ "$(grep -n 'feature_start render-action-log pass' "${d}/progress.md" | head -1 | cut -d: -f1)" -gt "$al" ] \
  || fail "leg1: bullet must appear after heading"
if grep -qF -- '_Record conductor handbacks' "${d}/progress.md"; then
  fail "leg1: placeholder must be replaced"
fi

# --- Leg 2: missing ## Action Log heading → exit 0, unchanged ---
d="${TMP_DIR}/l2"; mkdir -p "$d"; make_spans "${d}/trace.jsonl"
printf '# progress\n\nNo action log section.\n' > "${d}/progress.md"
assert_noop "leg2(missing-heading)" "${d}/progress.md" "${d}/trace.jsonl" 'action.log\|warn\|no.*action\|missing\|heading\|section'

# --- Leg 3: no agent spans → placeholder preserved (empty trace + non-agent-only) ---
d="${TMP_DIR}/l3"; mkdir -p "$d"; printf '' > "${d}/trace.jsonl"; scaffold_progress "$d"
bash "$RENDERER" "${d}/trace.jsonl" 2>/dev/null
grep -qF -- '- _Record conductor handbacks, subagent actions, review verdicts, and recovery notes here._' "${d}/progress.md" || fail "leg3: placeholder on empty trace"
d="${TMP_DIR}/l3b"; mkdir -p "$d"; scaffold_progress "$d"
printf '%s\n' '{"schema_version":1,"span":"lifecycle","span_id":"x1","harness.lifecycle_step":"worktree_create","harness.issue":332}' > "${d}/trace.jsonl"
bash "$RENDERER" "${d}/trace.jsonl" 2>/dev/null
grep -qF -- '- _Record conductor handbacks, subagent actions, review verdicts, and recovery notes here._' "${d}/progress.md" || fail "leg3b: placeholder when only non-agent spans"

# --- Leg 4: CLI edge cases — no args; missing trace; issue-number mode ---
rc=0; bash "$RENDERER" 2>/dev/null || rc=$?
[ "$rc" -eq 0 ] || fail "leg4a: no args must exit 0; got ${rc}"
rc=0; stderr="$(bash "$RENDERER" "${TMP_DIR}/nonexistent.jsonl" 2>&1)" || rc=$?
[ "$rc" -eq 0 ] || fail "leg4b: missing trace must exit 0; got ${rc}"
printf '%s\n' "$stderr" | grep -qi 'not found\|missing\|warn\|cannot\|no such' || fail "leg4b: must warn for missing trace"
nr="${TMP_DIR}/nr"; mkdir -p "$nr"; git_repo "$nr"
mkdir -p "${nr}/.copilot-tracking/issues/issue-07"; make_spans "${nr}/.copilot-tracking/issues/issue-07/trace.jsonl"
printf '# I7\n## Action Log\n- _placeholder_\n' > "${nr}/.copilot-tracking/issues/issue-07/progress.md"
rc=0; (cd "$nr" && bash "$RENDERER" 7 2>/dev/null) || rc=$?
[ "$rc" -eq 0 ] || fail "leg4c: issue-number mode must exit 0; got ${rc}"
grep -qF -- '- [conductor] feature_start' "${nr}/.copilot-tracking/issues/issue-07/progress.md" || fail "leg4c: must render bullets"

# --- Leg 5 (TEETH): mutant renderer wrong jq field → [conductor] absent ---
md="${TMP_DIR}/mutant"; mkdir -p "$md"
sed 's/gen_ai\.agent\.name/harness.lifecycle_step/g' "$RENDERER" > "${md}/render-action-log.sh"
chmod +x "${md}/render-action-log.sh"
d="${TMP_DIR}/l5"; mkdir -p "$d"; make_spans "${d}/trace.jsonl"; scaffold_progress "$d"
bash "${md}/render-action-log.sh" "${d}/trace.jsonl" 2>/dev/null
if grep -qF -- '- [conductor]' "${d}/progress.md"; then
  fail "leg5(TEETH): mutant still produces [conductor] — leg1 assertion would not catch wrong-field extraction"
fi
grep -qF -- '- [feature_start]' "${d}/progress.md" \
  || fail "leg5(TEETH): mutant must produce [feature_start]; mutation may not have applied"

# --- Leg 6: malformed JSON → warn + unchanged ---
d="${TMP_DIR}/l6"; mkdir -p "$d"; printf '{invalid json\n{also broken\n' > "${d}/trace.jsonl"
printf '# p\n## Action Log\n- [conductor] feature_start my-feature pass — existing bullet\n' > "${d}/progress.md"
assert_noop "leg6(malformed-json)" "${d}/progress.md" "${d}/trace.jsonl" 'warn\|parse\|fail\|error\|malform'

# --- Leg 7: unreadable trace → warn + unchanged (skipped as root) ---
if [ "$(id -u)" -eq 0 ]; then
  printf 'note: skipping leg7 (unreadable trace) — running as root\n'
else
  d="${TMP_DIR}/l7"; mkdir -p "$d"
  printf '{"span":"agent","gen_ai.agent.name":"conductor"}\n' > "${d}/trace.jsonl"; chmod 000 "${d}/trace.jsonl"
  printf '# p\n## Action Log\n- [conductor] feature_start my-feature pass — existing bullet\n' > "${d}/progress.md"
  assert_noop "leg7(unreadable-trace)" "${d}/progress.md" "${d}/trace.jsonl" 'warn\|fail\|error\|cannot\|permission\|read\|parse'
fi

# --- Leg 8: ## Action Log Archive not treated as ## Action Log ---
d="${TMP_DIR}/l8"; mkdir -p "$d"; make_spans "${d}/trace.jsonl"
printf '# I\n## Action Log\n- old\n## Action Log Archive\n- archived\n## Other\nother\n' > "${d}/progress.md"
bash "$RENDERER" "${d}/trace.jsonl" 2>/dev/null
grep -qF -- '## Action Log Archive' "${d}/progress.md" || fail "leg8: Archive heading must survive"
grep -qF -- '- archived' "${d}/progress.md" || fail "leg8: Archive content must survive"

# --- Leg 9: H1 boundary — # heading after ## Action Log preserved ---
d="${TMP_DIR}/l9"; mkdir -p "$d"; make_spans "${d}/trace.jsonl"
printf '# I\n## Action Log\n- old\n# Final Notes\nImportant final content.\n' > "${d}/progress.md"
bash "$RENDERER" "${d}/trace.jsonl" 2>/dev/null
grep -qF -- '# Final Notes' "${d}/progress.md" || fail "leg9: H1 heading must survive"
grep -qF -- 'Important final content.' "${d}/progress.md" || fail "leg9: H1 content must survive"

# --- Leg 10: permissions preserved after atomic replacement ---
d="${TMP_DIR}/l10"; mkdir -p "$d"; make_spans "${d}/trace.jsonl"; scaffold_progress "$d"
chmod 644 "${d}/progress.md"; bash "$RENDERER" "${d}/trace.jsonl" 2>/dev/null
perms="$(stat -c '%a' "${d}/progress.md" 2>/dev/null || stat -f '%OLp' "${d}/progress.md" 2>/dev/null || true)"
[ "$perms" = "644" ] || fail "leg10: permissions must be preserved; expected 644, got '${perms}'"

# --- Leg 11: bullets write failure → warn + unchanged (root-safe via dir target) ---
# Fake mktemp converts render-bullets target to a dir; printf→dir fails even as root.
REAL_MKTEMP="$(command -v mktemp)"
d="${TMP_DIR}/l11"; mkdir -p "${d}/fb"; fakebin "${d}/fb" chmod 'exit 0'
cat > "${d}/fb/mktemp" <<MKEOF
#!/usr/bin/env bash
r="\$("${REAL_MKTEMP}" "\$@")" || exit \$?
for a in "\$@"; do last="\$a"; done
case "\$last" in *render-bullets*) rm -f "\$r"; mkdir "\$r" ;; esac
printf '%s\n' "\$r"
MKEOF
chmod +x "${d}/fb/mktemp"
make_spans "${d}/trace.jsonl"; scaffold_progress "$d"
assert_noop_path "leg11(bullets-write-fail)" "${d}/progress.md" "${d}/trace.jsonl" 'warn\|fail\|write\|bullet\|temp' "${d}/fb"

# --- Leg 12: live layout — issue-number mode finds worktree progress.md ---
mr="${TMP_DIR}/mr12"; wt="${TMP_DIR}/wt12"; mkdir -p "$mr"; git_repo "$mr"
git -C "$mr" worktree add -q "$wt" -b leg12
mkdir -p "${mr}/.copilot-tracking/issues/issue-12"; make_spans "${mr}/.copilot-tracking/issues/issue-12/trace.jsonl"
mkdir -p "${wt}/.copilot-tracking/issues/issue-12"
printf '# I12\n## Action Log\n- _placeholder_\n' > "${wt}/.copilot-tracking/issues/issue-12/progress.md"
rc=0; (cd "$wt" && bash "$RENDERER" 12 2>/dev/null) || rc=$?
[ "$rc" -eq 0 ] || fail "leg12: live-layout must exit 0; got ${rc}"
grep -qF -- '- [conductor] feature_start render-action-log pass' \
  "${wt}/.copilot-tracking/issues/issue-12/progress.md" || fail "leg12: must render bullets into worktree progress.md"

# --- Leg 13: symlink rejection — progress.md symlink (13a) and trace dir symlink (13b) ---
da="${TMP_DIR}/l13a"; dt="${TMP_DIR}/l13a-t"; mkdir -p "$da" "$dt"; make_spans "${da}/trace.jsonl"
printf '# p\n## Action Log\n- _placeholder_\n' > "${dt}/real.md"; ln -s "${dt}/real.md" "${da}/progress.md"
assert_noop "leg13a(symlink-progress)" "${dt}/real.md" "${da}/trace.jsonl" 'symlink\|warn\|redirect\|link'
db="${TMP_DIR}/l13b-real"; mkdir -p "$db"; make_spans "${db}/trace.jsonl"; scaffold_progress "$db"
ln -s "$db" "${TMP_DIR}/l13b-link"
assert_noop "leg13b(symlink-dir)" "${db}/progress.md" "${TMP_DIR}/l13b-link/trace.jsonl" 'symlink\|warn\|redirect\|link'

# --- Leg 14: non-object JSON (array, null, number) → warn + unchanged (table-driven) ---
for noval in '[]' 'null' '42'; do
  d="${TMP_DIR}/l14-${noval//[^a-z0-9]/-}"; mkdir -p "$d"
  printf '%s\n' "$noval" > "${d}/trace.jsonl"
  printf '# p\n## Action Log\n- [conductor] feature_start my-feature pass — real existing bullet\n' > "${d}/progress.md"
  assert_noop "leg14(${noval})" "${d}/progress.md" "${d}/trace.jsonl" 'warn\|parse\|fail\|error\|object\|non-object\|json'
done

# --- Leg 15: ancestor symlink → trace dir logical path traverses symlink → warn + unchanged ---
dr="${TMP_DIR}/l15-real"; mkdir -p "${dr}/issue-dir"; make_spans "${dr}/issue-dir/trace.jsonl"
printf '# p\n## Action Log\n- [conductor] feature_start my-feature pass — real existing bullet\n' > "${dr}/issue-dir/progress.md"
ln -s "$dr" "${TMP_DIR}/l15-link"
assert_noop "leg15(ancestor-symlink)" "${dr}/issue-dir/progress.md" "${TMP_DIR}/l15-link/issue-dir/trace.jsonl" \
  'symlink\|warn\|redirect\|link\|travers\|ancestor\|component'

# --- Leg 16: mode fault injection (stat fail, chmod fail) → warn + unchanged (table-driven) ---
for fault in stat chmod; do
  d="${TMP_DIR}/l16-${fault}"; mkdir -p "${d}/fb"; fakebin "${d}/fb" "$fault" 'exit 1'
  make_spans "${d}/trace.jsonl"
  printf '# p\n## Action Log\n- [conductor] feature_start my-feature pass — real existing bullet\n' > "${d}/progress.md"
  assert_noop_path "leg16(${fault}-fail)" "${d}/progress.md" "${d}/trace.jsonl" \
    'warn\|perm\|stat\|mode\|fail\|chmod\|retriev\|apply' "${d}/fb"
done

# --- Leg 17: research-field span → core five-field bullet only (no research suffix) ---
d="${TMP_DIR}/l17"; mkdir -p "$d"; scaffold_progress "$d"
printf '%s\n' '{"schema_version":1,"span":"agent","span_id":"r1","timestamp":"2026-07-01T00:00:00Z","gen_ai.operation.name":"invoke_agent","gen_ai.agent.name":"generator-subagent","harness.lifecycle_step":"green_handback","harness.feature_id":"some-research-feature","harness.outcome":"pass","harness.summary":"completed with research","harness.issue":332,"harness.research_url":"https://example.com/doc","harness.research_summary":"consulted docs page"}' > "${d}/trace.jsonl"
bash "$RENDERER" "${d}/trace.jsonl" 2>/dev/null
grep -qF -- '- [generator-subagent] green_handback some-research-feature pass — completed with research' \
  "${d}/progress.md" || fail "leg17: research span must render core five-field bullet"
if grep -q 'research:' "${d}/progress.md"; then
  fail "leg17: must not add a research: annotation — Action Log is core five fields only"
fi

printf 'ok - all legs passed\n'
)
